"""init_db

Revision ID: 7e82150eaa17
Revises: 
Create Date: 2023-01-30 16:31:32.683430

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = "7e82150eaa17"
down_revision = None
branch_labels = None
depends_on = None


def _has_table(name: str) -> bool:
    from sqlalchemy import inspect

    insp = inspect(op.get_bind())
    return name in insp.get_table_names()


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if _has_table("cchess_game_record"):
        op.rename_table("cchess_game_record", "nonebot_plugin_cchess_gamerecord")
    else:
        op.create_table(
            "nonebot_plugin_cchess_gamerecord",
            sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column("session_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column("start_time", sa.DateTime(), nullable=False),
            sa.Column("update_time", sa.DateTime(), nullable=False),
            sa.Column(
                "player_red_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False
            ),
            sa.Column(
                "player_red_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False
            ),
            sa.Column(
                "player_black_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False
            ),
            sa.Column(
                "player_black_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False
            ),
            sa.Column("start_fen", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column("moves", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column("is_game_over", sa.Boolean(), nullable=False),
            sa.PrimaryKeyConstraint("id"),
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("nonebot_plugin_cchess_gamerecord")
    # ### end Alembic commands ###
