"""add_game_id

Revision ID: 8e24973393ea
Revises: 7e82150eaa17
Create Date: 2023-01-30 16:42:34.288320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8e24973393ea"
down_revision = "7e82150eaa17"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "nonebot_plugin_cchess_gamerecord", schema=None
    ) as batch_op:
        batch_op.alter_column("id", new_column_name="game_id")
        batch_op.add_column(
            sa.Column(
                "id", sa.Integer(), nullable=False, primary_key=True, autoincrement=True
            )
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "nonebot_plugin_cchess_gamerecord", schema=None
    ) as batch_op:
        batch_op.drop_column("id")
        batch_op.alter_column("game_id", new_column_name="id")
    # ### end Alembic commands ###
